name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

# Add regular dependencies here.
dependencies:
  persian:
    path: ../

dev_dependencies:
  lints: ^2.0.0
  test: ^1.22.0
