name: persian
description: Utilities and Humanizer for Persian language and culture. Includes some String extensions and PersianDate class. 
version: 2.0.0
repository: https://github.com/olutter/persian
homepage: https://pwa.ir


environment:
  sdk: ">=2.12.0 <4.0.0"

dev_dependencies:
  test: ^1.26.0
  lints: ^6.0.0
