name: persian
description: Utilities for Persian language/culture. Includes some String extensions and PersianDate class. 
version: 1.1.0
repository: https://github.com/xclud/persian
homepage: https://pwa.ir


environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

dev_dependencies:
  test: ^1.17.3