name: persian
description: Utilities for Persian language/culture. Includes some String extensions and PersianDate class. 
version: 1.0.0
homepage: https://github.com/xclud/persian

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:

dev_dependencies:
  test: ^1.3.0