name: persian
description: Utilities and Humanizer for Persian language and culture. Includes some String extensions and PersianDate class. 
version: 1.2.0
repository: https://github.com/xclud/dart_persian
homepage: https://pwa.ir


environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  test: ^1.22.0
  lints: ^2.0.1
