name: persian
description: Utilities for Persian language/culture. Includes some String extensions and PersianDate class. 
version: 0.1.5+1
homepage: https://github.com/xclud/persian

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:

dev_dependencies:
  test: ^1.3.0